// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Beer struct {
	ID       int64
	Name     string
	BrewerID sql.NullInt64
	Style    sql.NullString
	Abv      float64
	Rating   sql.NullFloat64
	Notes    sql.NullString
}

type Brewer struct {
	ID       int64
	Name     string
	Location sql.NullString
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
	LastLogin    sql.NullTime
}
